### PR TITLE
Fix dependencies for the most recent Dart version

### LINKED ISSUE #41: Fails to compile on Dart 2.13.4 (most likely dependencies problem)
I created a fresh Dart project:

```
$ dart --version
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_arm
$ dart create -t web-simple my_project
```

Then I added the latest version of `pwa` to `pubspec.yaml`:

```
dependencies:
  pwa: ^0.2.0
```

(I also tried with 0.1.2, the outcome was the same.)

Then calling `pub get` downgraded versions of many packages:

```
$ pub get
Resolving dependencies... (4.3s)
< _fe_analyzer_shared 14.0.0 (was 22.0.0) (24.0.0
< analyzer 0.41.2 (was 1.7.2) (2.1.0 available)
< args 1.6.0 (was 2.2.0) (2.2.0 available)
< build 1.6.2 (was 2.0.3) (2.1.0 available)
< build_config 0.4.5 (was 0.4.7) (1.0.0 available)
  build_daemon 2.1.10 (3.0.0 available)
< build_modules 3.0.4 (was 3.0.6) (4.0.2 available)
< build_resolvers 1.5.3 (was 2.0.4) (2.0.4 available)
< build_runner 1.11.1+1 (was 1.12.2) (2.1.1 available)
< build_runner_core 6.1.7 (was 6.1.12) (7.1.0 available)
< build_web_compilers 2.16.3 (was 2.16.5) (3.2.1 available)
< checked_yaml 1.0.4 (was 2.0.1) (2.0.1 available)
+ clock 1.1.0
  code_builder 3.7.0 (4.1.0 available)
< dart_style 1.3.12 (was 2.0.3) (2.0.3 available)
< file 5.2.1 (was 6.1.2) (6.1.2 available)
< glob 1.2.0 (was 2.0.1) (2.0.1 available)
< graphs 0.2.0 (was 1.0.0) (2.0.0 available)
< http_multi_server 2.2.0 (was 3.0.1) (3.0.1 available)
+ intl 0.17.0
< io 0.3.5 (was 1.0.3) (1.0.3 available)
+ node_interop 1.2.1 (2.0.2 available)
+ node_io 1.2.0 (2.1.0 available)
< package_config 1.9.3 (was 2.0.0) (2.0.0 available)
< pubspec_parse 0.1.8 (was 1.0.0) (1.0.0 available)
+ pwa 0.2.0
< scratch_space 0.0.4+3 (was 1.0.0) (1.0.0 available)
+ service_worker 0.2.4
< shelf_web_socket 0.2.4+1 (was 1.0.1) (1.0.1 available)
< timing 0.1.1+3 (was 1.0.0) (1.0.0 available)
< web_socket_channel 1.2.0 (was 2.1.0) (2.1.0 available)
< yaml 2.2.1 (was 3.1.0) (3.1.0 available)
Changed 30 dependencies!
```

As a result the project doesn't compile any more:

```
$ webdev serve
[SEVERE] Failed to precompile build_runner:build_runner:
[SEVERE] /home/p/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/src/error/best_practices_verifier.dart:258:50: Error: The property 'displayString' is defined in multiple
 extensions for 'TargetKind' and neither is more specific.
[SEVERE]  - 'TargetKind' is from 'package:meta/meta_meta.dart' ('/home/p/.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart').
[SEVERE] Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
[SEVERE]         var kindNames = kinds.map((kind) => kind.displayString).toList()
[SEVERE]                                                  ^^^^^^^^^^^^^
[SEVERE] /home/p/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/src/error/best_practices_verifier.dart:1950:14: Context: This is one of the extension members.
[SEVERE]   String get displayString {
[SEVERE]              ^^^^^^^^^^^^^
[SEVERE] /home/p/.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart:91:14: Context: This is one of the extension members.
[SEVERE]   String get displayString {
[SEVERE]              ^^^^^^^^^^^^^
[SEVERE] /home/p/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/src/error/best_practices_verifier.dart:260:36: Error: The getter 'commaSeparatedWithOr' isn't defined for
 the class 'List<dynamic>'.
[SEVERE]  - 'List' is from 'dart:core'.
[SEVERE] Try correcting the name to the name of an existing getter, or defining a getter or field named 'commaSeparatedWithOr'.
[SEVERE]         var validKinds = kindNames.commaSeparatedWithOr;
[SEVERE]                                    ^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
Bad state: Unable to start build daemon.
...
```

Any idea how this can be fixed? Thanks!

### PR DESCRIPTION
**Pull request by ppetr**
Fixes #41.

### CODE REVIEW

**Comment by ppetr** [comment]
Looks like the next step will be to migrate the package wrt `null`-safety. The error I'm getting now is

> Error: Cannot run with sound null safety, because the following dependencies don't support null safety:                                                                                                                                                      
>
> - package:service_worker
>
> For solutions, see https://dart.dev/go/unsound-null-safety

**Comment by isoos** [comment]
> Error: Cannot run with sound null safety, because the following dependencies don't support null safety:
> package:service_worker

Yeah, ideally `package:service_worker` is migrated first (I'm the maintainer of that too, so same time constraints applies).

**Comment by isoos** [comment]
Have you tried if these constraints are working for you?

**Comment by ppetr** [comment]
Yes, I've tested that the updated dependencies work. I'll have a look at `service_worker` too.

**Comment by isoos** [comment]
published :)

**Pull request merged**
